# Generated by Django 5.2.4 on 2025-07-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
